import { jsPDF } from "jspdf";
import type { AssessmentResult } from "./types";

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9]/gi, "-").replace(/-+/g, "-") || "report";
}

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export function generateAssessmentPdf(result: AssessmentResult): void {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = 24;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(10, 22, 40);
  doc.text("D1 Leadership Assessment Report", margin, y);

  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("D1 Frontline Leadership", margin, y);

  y += 14;
  doc.setDrawColor(201, 162, 39);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Candidate Information", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  doc.text(`Candidate: ${result.intro.candidateName}`, margin, y);
  y += 6;
  doc.text(`Role: ${result.intro.role}`, margin, y);
  y += 6;
  doc.text(`Evaluator: ${result.intro.evaluatorName}`, margin, y);
  y += 6;
  doc.text(`Date: ${new Date().toLocaleDateString("en-US")}`, margin, y);

  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(10, 22, 40);
  doc.text(`Overall D1 Score: ${result.overallScore}/100`, margin, y);

  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(201, 162, 39);
  doc.text(result.category.label, margin, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  y = addWrappedText(doc, result.category.description, margin, y, contentWidth, 5);

  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Trait Breakdown", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const trait of result.traitScores) {
    doc.setTextColor(40, 40, 40);
    doc.text(`${trait.name}: ${trait.score}%`, margin, y);
    y += 6;
  }

  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Strengths", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const item of result.strengths) {
    y = addWrappedText(doc, `• ${item}`, margin, y, contentWidth, 5);
    y += 2;
  }

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Development Areas", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const item of result.developmentAreas) {
    y = addWrappedText(doc, `• ${item}`, margin, y, contentWidth, 5);
    y += 2;
  }

  if (y > 240) {
    doc.addPage();
    y = 24;
  }

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Development Recommendations", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const item of result.recommendations) {
    y = addWrappedText(doc, `• ${item}`, margin, y, contentWidth, 5);
    y += 2;
    if (y > 270) {
      doc.addPage();
      y = 24;
    }
  }

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.text("Suggested Next Steps", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const item of result.nextSteps) {
    y = addWrappedText(doc, `• ${item}`, margin, y, contentWidth, 5);
    y += 2;
  }

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by D1 Frontline Leadership | d1frontlineleadership.com",
    margin,
    doc.internal.pageSize.getHeight() - 12,
  );

  doc.save(
    `D1-Leadership-Assessment-${sanitizeFilename(result.intro.candidateName)}.pdf`,
  );
}
